

class of07
{
	attributes:

	methods:

		int t1(int a, int b, int c, int d)
		{
			print(a);
			print(b);
			print(c);
			print(d);
		}

		int factorial(int n)
		{
			if (n <= 1)
			{
				return 1;
			}

			return n * factorial(n - 1);
		}

		int main()
		{
			int foo;
			int factorialn;

			foo = t1(321 + 5 + 2, 1, 2, 3);

			print(123);

			factorialn = 5;

			print(factorialn);
			print(factorial(factorialn));
			print(factorialn);
		}
}